#!/bin/sh

#
# Author: Arkadiusz Dzięgiel <arkadiusz.dziegiel@glorpen.pl>
#

runsvdir="/opt/puppetizer/bin/runsvdir"

do_init(){
    puppet_apply || kill -TERM 0
    
    touch "${puppetizer_initialized_token}"
    echo "Container marked as initialized"
}

_wait_for_runsvdir(){
    while :;
    do
        pkill -0 -f "${runsvdir}"
        if [ $? -eq 0 ];
        then
            return 0
        fi
        sleep 1s
    done
}

delayed_start(){
    . /opt/puppetizer/share/common.sh
    
    _wait_for_runsvdir && do_init
}

delayed_start &

exec ${runsvdir} /opt/puppetizer/service
