#!/bin/sh

#
# Author: Arkadiusz Dzięgiel <arkadiusz.dziegiel@glorpen.pl>
#

runsvdir="/opt/puppetizer/bin/runsvdir"

set -e

do_init(){
    puppet_apply
}

delayed_start(){
    . /opt/puppetizer/share/common.sh
    
    while :;
    do
        pkill -0 -f "${runsvdir}" && ( do_init; exit 0 ) 
        sleep 1s
    done
}

delayed_start &

exec ${runsvdir} /opt/puppetizer/service
