#!/bin/sh

#
# Author: Arkadiusz Dzięgiel <arkadiusz.dziegiel@glorpen.pl>
#

echo "?? run"

. /opt/puppetizer/share/common.sh

on_exit(){
    echo "handler gracefull exit"
    kill -HUP %1
    wait
    exit 0
}

on_reload(){
    echo "Reapplying configuration..."
    puppet_apply
    echo "Configuration applied."
}

trap '{ on_exit; }' TERM
trap '{ on_reload; }' HUP

/opt/puppetizer/bin/runsvdir /opt/puppetizer/service &

while :; do wait; done
